version: "3"

services:
  # app:
  #   container_name: api-valoriza
  #   build: .
  #   command: yarn dev
  #   ports:
  #     - "3333:3333"
  #   volumes:
  #     - .:/usr/app

  database:
    container_name: db-valoriza
    image: mysql:5.7.31
    command: --default-authentication-plugin=mysql_native_password --sql_mode=NO_ENGINE_SUBSTITUTION,NO_AUTO_CREATE_USER --explicit_defaults_for_timestamp
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: nlw-together
      MYSQL_DATABASE: valoriza
      MYSQL_USER: valoriza-user
      MYSQL_PASSWORD: valoriza-password
